import { PRICING } from '@/lib/pricing';
import type {
  CatalogItem,
  CompanyEligibilityConfiguration,
  EligibilityFieldDefinition,
  EligibilityFieldKey,
  EligibilityImportTemplate,
  ProgramBucket,
  ProgramBucketItem,
} from '@/lib/ordering-domain';

export const CATALOG_ITEMS: CatalogItem[] = [
  {
    id: 'catalog-eu-compliance',
    code: 'EU_PACKAGE_COMPLIANCE',
    name: 'Compliance',
    description: 'Base EU package for compliance-oriented company programs.',
    itemType: 'package',
    category: 'eu_package',
    status: 'active',
    defaultAmount: PRICING.euAllowancePerEmployee.Compliance,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 10,
  },
  {
    id: 'catalog-eu-comfort',
    code: 'EU_PACKAGE_COMFORT',
    name: 'Comfort',
    description: 'Base EU package for broader employee program coverage.',
    itemType: 'package',
    category: 'eu_package',
    status: 'active',
    defaultAmount: PRICING.euAllowancePerEmployee.Comfort,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 20,
  },
  {
    id: 'catalog-eu-complete',
    code: 'EU_PACKAGE_COMPLETE',
    name: 'Complete',
    description: 'Base EU package for the most inclusive default coverage set.',
    itemType: 'package',
    category: 'eu_package',
    status: 'active',
    defaultAmount: PRICING.euAllowancePerEmployee.Complete,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 30,
  },
  {
    id: 'catalog-service-essential',
    code: 'SERVICE_TIER_ESSENTIAL',
    name: 'Essential',
    description: 'Base service tier for program setup and recurring support.',
    itemType: 'service_tier',
    category: 'service_tier',
    status: 'active',
    defaultAmount: PRICING.serviceFeePerEmployee.Essential,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 40,
  },
  {
    id: 'catalog-service-access',
    code: 'SERVICE_TIER_ACCESS',
    name: 'Access',
    description: 'Expanded service tier for higher-touch program operations.',
    itemType: 'service_tier',
    category: 'service_tier',
    status: 'active',
    defaultAmount: PRICING.serviceFeePerEmployee.Access,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 50,
  },
  {
    id: 'catalog-service-premier',
    code: 'SERVICE_TIER_PREMIER',
    name: 'Premier',
    description: 'Highest active service tier for recurring program support.',
    itemType: 'service_tier',
    category: 'service_tier',
    status: 'active',
    defaultAmount: PRICING.serviceFeePerEmployee.Premier,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 60,
  },
  {
    id: 'catalog-addon-anti-fog',
    code: 'ADD_ON_ANTI_FOG',
    name: 'Anti-Fog',
    description: 'Program add-on for anti-fog lens treatment.',
    itemType: 'add_on',
    category: 'program_add_on',
    status: 'active',
    defaultAmount: PRICING.euPackageAddOnsPerEmployee.antiFog,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 70,
  },
  {
    id: 'catalog-addon-anti-reflective-standard',
    code: 'ADD_ON_ANTI_REFLECTIVE_STANDARD',
    name: 'Anti-Reflective Standard',
    description: 'Program add-on for standard anti-reflective treatment.',
    itemType: 'add_on',
    category: 'program_add_on',
    status: 'active',
    defaultAmount: PRICING.euPackageAddOnsPerEmployee.antiReflectiveStd,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 80,
  },
  {
    id: 'catalog-addon-blue-light-filter',
    code: 'ADD_ON_BLUE_LIGHT_FILTER',
    name: 'Blue Light Filter',
    description: 'Program add-on for blue light filtering lenses.',
    itemType: 'add_on',
    category: 'program_add_on',
    status: 'active',
    defaultAmount: PRICING.euPackageAddOnsPerEmployee.blueLightFilter,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 90,
  },
  {
    id: 'catalog-addon-transitions',
    code: 'ADD_ON_TRANSITIONS',
    name: 'Transitions',
    description: 'Program add-on for light-reactive transition lenses.',
    itemType: 'add_on',
    category: 'program_add_on',
    status: 'active',
    defaultAmount: PRICING.euPackageAddOnsPerEmployee.transitions,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 100,
  },
  {
    id: 'catalog-support-extra-site-visit',
    code: 'SUPPORT_EXTRA_SITE_VISIT',
    name: 'Extra Site Visit',
    description: 'Support item for additional on-site visits outside the base tier.',
    itemType: 'support',
    category: 'support',
    status: 'active',
    defaultAmount: PRICING.extraSiteVisitFee,
    currency: 'USD',
    isProgramAssignable: true,
    isOrderSelectable: false,
    isBillable: true,
    displayOrder: 110,
  },
];

export const PROGRAM_BUCKETS: ProgramBucket[] = [
  {
    id: 'bucket-eu-compliance',
    code: 'EU_COMPLIANCE',
    name: 'EU Compliance',
    bucketType: 'eu_package',
    displayOrder: 10,
    status: 'active',
  },
  {
    id: 'bucket-eu-comfort',
    code: 'EU_COMFORT',
    name: 'EU Comfort',
    bucketType: 'eu_package',
    displayOrder: 20,
    status: 'active',
  },
  {
    id: 'bucket-eu-complete',
    code: 'EU_COMPLETE',
    name: 'EU Complete',
    bucketType: 'eu_package',
    displayOrder: 30,
    status: 'active',
  },
  {
    id: 'bucket-service-essential',
    code: 'SERVICE_ESSENTIAL',
    name: 'Service Essential',
    bucketType: 'service_tier',
    displayOrder: 40,
    status: 'active',
  },
  {
    id: 'bucket-service-access',
    code: 'SERVICE_ACCESS',
    name: 'Service Access',
    bucketType: 'service_tier',
    displayOrder: 50,
    status: 'active',
  },
  {
    id: 'bucket-service-premier',
    code: 'SERVICE_PREMIER',
    name: 'Service Premier',
    bucketType: 'service_tier',
    displayOrder: 60,
    status: 'active',
  },
];

export const PROGRAM_BUCKET_ITEMS: ProgramBucketItem[] = [
  { bucketCode: 'EU_COMPLIANCE', catalogItemCode: 'EU_PACKAGE_COMPLIANCE', displayOrder: 10 },
  { bucketCode: 'EU_COMFORT', catalogItemCode: 'EU_PACKAGE_COMFORT', displayOrder: 10 },
  { bucketCode: 'EU_COMPLETE', catalogItemCode: 'EU_PACKAGE_COMPLETE', displayOrder: 10 },
  { bucketCode: 'SERVICE_ESSENTIAL', catalogItemCode: 'SERVICE_TIER_ESSENTIAL', displayOrder: 10 },
  { bucketCode: 'SERVICE_ACCESS', catalogItemCode: 'SERVICE_TIER_ACCESS', displayOrder: 10 },
  { bucketCode: 'SERVICE_PREMIER', catalogItemCode: 'SERVICE_TIER_PREMIER', displayOrder: 10 },
];

export const DEFAULT_ELIGIBILITY_FIELD_DEFINITIONS: EligibilityFieldDefinition[] = [
  {
    key: 'employeeId',
    label: 'Employee ID',
    required: false,
    fieldType: 'text',
    description: 'Stable employer-provided employee identifier.',
    example: 'E12345',
  },
  {
    key: 'firstName',
    label: 'First Name',
    required: true,
    fieldType: 'text',
    description: 'Employee legal or roster first name.',
    example: 'Jordan',
  },
  {
    key: 'lastName',
    label: 'Last Name',
    required: true,
    fieldType: 'text',
    description: 'Employee legal or roster last name.',
    example: 'Lee',
  },
  {
    key: 'email',
    label: 'Email',
    required: false,
    fieldType: 'email',
    description: 'Employee work or personal email when available.',
    example: 'jordan.lee@example.com',
  },
  {
    key: 'companyId',
    label: 'Company ID',
    required: false,
    fieldType: 'text',
    description: 'Internal company identifier used by the ordering system.',
    example: 'ACME-WEST',
  },
  {
    key: 'department',
    label: 'Department',
    required: false,
    fieldType: 'text',
    description: 'Department or cost center grouping from the employer.',
    example: 'Warehouse',
  },
  {
    key: 'location',
    label: 'Location',
    required: false,
    fieldType: 'text',
    description: 'Primary work location or site name.',
    example: 'Phoenix DC',
  },
  {
    key: 'eligibilityStatus',
    label: 'Eligibility Status',
    required: false,
    fieldType: 'select',
    description: 'Normalized eligibility decision for the employee.',
    example: 'eligible',
  },
  {
    key: 'hireDate',
    label: 'Hire Date',
    required: false,
    fieldType: 'date',
    description: 'Hire date used for program waiting periods when applicable.',
    example: '2026-01-15',
  },
  {
    key: 'allowanceGroup',
    label: 'Allowance Group',
    required: false,
    fieldType: 'text',
    description: 'Optional group used to map coverage or pricing variations.',
    example: 'Manufacturing Annual',
  },
  {
    key: 'notes',
    label: 'Notes',
    required: false,
    fieldType: 'textarea',
    description: 'Employer-supplied notes that should travel with the intake row.',
    example: 'Supervisor approval required for specialty add-ons.',
  },
];

export const DEFAULT_ELIGIBILITY_IMPORT_TEMPLATE: EligibilityImportTemplate = {
  id: 'eligibility-template-default',
  code: 'DEFAULT_EMPLOYER_ELIGIBILITY',
  name: 'Default Employer Eligibility Intake',
  description: 'Baseline company roster template for employee program eligibility intake.',
  companyId: null,
  fieldDefinitions: DEFAULT_ELIGIBILITY_FIELD_DEFINITIONS,
};

export const DEFAULT_COMPANY_ELIGIBILITY_CONFIGURATION: CompanyEligibilityConfiguration = {
  companyId: null,
  templateId: DEFAULT_ELIGIBILITY_IMPORT_TEMPLATE.id,
  requiredFieldKeys: DEFAULT_ELIGIBILITY_FIELD_DEFINITIONS.filter((field) => field.required).map(
    (field) => field.key
  ),
  optionalFieldKeys: DEFAULT_ELIGIBILITY_FIELD_DEFINITIONS.filter((field) => !field.required).map(
    (field) => field.key
  ),
  allowAdditionalFields: false,
};

export const CATALOG_ITEMS_BY_CODE = Object.fromEntries(
  CATALOG_ITEMS.map((item) => [item.code, item])
) as Record<string, CatalogItem>;

export const PROGRAM_BUCKETS_BY_CODE = Object.fromEntries(
  PROGRAM_BUCKETS.map((bucket) => [bucket.code, bucket])
) as Record<ProgramBucket['code'], ProgramBucket>;

export const ELIGIBILITY_FIELDS_BY_KEY = Object.fromEntries(
  DEFAULT_ELIGIBILITY_FIELD_DEFINITIONS.map((field) => [field.key, field])
) as Record<EligibilityFieldKey, EligibilityFieldDefinition>;
